const js = [
    {
      contactID: "75e671b1-13ef-41e4-a6d4-bd2518cf6160",
      mergedToContactID: undefined,
      contactNumber: undefined,
      accountNumber: undefined,
      contactStatus: "ACTIVE",
      name: "A.B. Controls & Technology Inc",
      firstName: "Karl",
      lastName: "Wighaman",
      companyNumber: undefined,
      emailAddress: "support@abtech-inc.com",
      skypeUserName: undefined,
      contactPersons: [
      ],
      bankAccountDetails: undefined,
      taxNumber: undefined,
      accountsReceivableTaxType: undefined,
      accountsPayableTaxType: undefined,
      addresses: [
        {
          addressType: "POBOX",
          addressLine1: "1813 Rotary Dr",
          addressLine2: undefined,
          addressLine3: undefined,
          addressLine4: undefined,
          city: "Humble",
          region: "TX",
          postalCode: "77338",
          country: "USA",
          attentionTo: "Geoff Amos",
        },
        {
          addressType: "STREET",
          addressLine1: "1813 Rotary Dr",
          addressLine2: undefined,
          addressLine3: undefined,
          addressLine4: undefined,
          city: "Humble",
          region: "TX",
          postalCode: "77338",
          country: "USA",
          attentionTo: "Geoff Amos",
        },
      ],
      phones: [
        {
          phoneType: "DDI",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
        {
          phoneType: "DEFAULT",
          phoneNumber: "548-3424",
          phoneAreaCode: "281",
          phoneCountryCode: "1",
        },
        {
          phoneType: "FAX",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
        {
          phoneType: "MOBILE",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
      ],
      isSupplier: false,
      isCustomer: true,
      salesDefaultLineAmountType: undefined,
      purchasesDefaultLineAmountType: undefined,
      defaultCurrency: "USD",
      xeroNetworkKey: undefined,
      salesDefaultAccountCode: undefined,
      purchasesDefaultAccountCode: undefined,
      salesTrackingCategories: undefined,
      purchasesTrackingCategories: undefined,
      trackingCategoryName: undefined,
      trackingCategoryOption: undefined,
      paymentTerms: {
        bills: undefined,
        sales: {
          day: 0,
          type: "DAYSAFTERBILLDATE",
        },
      },
      updatedDateUTC: {
      },
      contactGroups: [
      ],
      website: "https://www.abtech-inc.com/",
      brandingTheme: undefined,
      batchPayments: undefined,
      discount: undefined,
      balances: {
        accountsReceivable: {
          outstanding: 3362.87,
          overdue: 3362.87,
        },
        accountsPayable: {
          outstanding: 0,
          overdue: 0,
        },
      },
      attachments: undefined,
      hasAttachments: false,
      validationErrors: undefined,
      hasValidationErrors: false,
      statusAttributeString: undefined,
    },
    {
      contactID: "4ab3a499-51e7-45b0-b566-4ac5506dd858",
      mergedToContactID: undefined,
      contactNumber: undefined,
      accountNumber: "21-788762",
      contactStatus: "ACTIVE",
      name: "Sophos (Ingram Micro)",
      firstName: "Sophos",
      lastName: "Licensing",
      companyNumber: undefined,
      emailAddress: "Sophos-Licensing@ingrammicro.com",
      skypeUserName: undefined,
      contactPersons: [
      ],
      bankAccountDetails: undefined,
      taxNumber: undefined,
      accountsReceivableTaxType: undefined,
      accountsPayableTaxType: undefined,
      addresses: [
        {
          addressType: "POBOX",
          addressLine1: undefined,
          addressLine2: undefined,
          addressLine3: undefined,
          addressLine4: undefined,
          city: undefined,
          region: undefined,
          postalCode: undefined,
          country: undefined,
          attentionTo: undefined,
        },
        {
          addressType: "STREET",
          addressLine1: undefined,
          addressLine2: undefined,
          addressLine3: undefined,
          addressLine4: undefined,
          city: undefined,
          region: undefined,
          postalCode: undefined,
          country: undefined,
          attentionTo: undefined,
        },
      ],
      phones: [
        {
          phoneType: "DDI",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
        {
          phoneType: "DEFAULT",
          phoneNumber: "456-8000",
          phoneAreaCode: "800",
          phoneCountryCode: "+1",
        },
        {
          phoneType: "FAX",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
        {
          phoneType: "MOBILE",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
      ],
      isSupplier: true,
      isCustomer: false,
      salesDefaultLineAmountType: undefined,
      purchasesDefaultLineAmountType: undefined,
      defaultCurrency: "USD",
      xeroNetworkKey: undefined,
      salesDefaultAccountCode: undefined,
      purchasesDefaultAccountCode: undefined,
      salesTrackingCategories: undefined,
      purchasesTrackingCategories: undefined,
      trackingCategoryName: undefined,
      trackingCategoryOption: undefined,
      paymentTerms: undefined,
      updatedDateUTC: {
      },
      contactGroups: [
      ],
      website: "https://usa.ingrammicro.com/cep/app/my/dashboard",
      brandingTheme: undefined,
      batchPayments: undefined,
      discount: undefined,
      balances: {
        accountsReceivable: {
          outstanding: 0,
          overdue: 0,
        },
        accountsPayable: {
          outstanding: 1595.38,
          overdue: 1595.38,
        },
      },
      attachments: undefined,
      hasAttachments: false,
      validationErrors: undefined,
      hasValidationErrors: false,
      statusAttributeString: undefined,
    },
    {
      contactID: "e762f989-5702-43e7-b026-1accb8e50330",
      mergedToContactID: undefined,
      contactNumber: undefined,
      accountNumber: undefined,
      contactStatus: "ACTIVE",
      name: "Unassigned",
      firstName: undefined,
      lastName: undefined,
      companyNumber: undefined,
      emailAddress: "",
      skypeUserName: undefined,
      contactPersons: [
      ],
      bankAccountDetails: "",
      taxNumber: undefined,
      accountsReceivableTaxType: undefined,
      accountsPayableTaxType: undefined,
      addresses: [
        {
          addressType: "STREET",
          addressLine1: undefined,
          addressLine2: undefined,
          addressLine3: undefined,
          addressLine4: undefined,
          city: "",
          region: "",
          postalCode: "",
          country: "Unknown",
          attentionTo: undefined,
        },
        {
          addressType: "POBOX",
          addressLine1: undefined,
          addressLine2: undefined,
          addressLine3: undefined,
          addressLine4: undefined,
          city: "",
          region: "",
          postalCode: "",
          country: "",
          attentionTo: undefined,
        },
      ],
      phones: [
        {
          phoneType: "DDI",
          phoneNumber: "",
          phoneAreaCode: "",
          phoneCountryCode: "",
        },
        {
          phoneType: "DEFAULT",
          phoneNumber: "",
          phoneAreaCode: "",
          phoneCountryCode: "",
        },
        {
          phoneType: "FAX",
          phoneNumber: "",
          phoneAreaCode: "",
          phoneCountryCode: "",
        },
        {
          phoneType: "MOBILE",
          phoneNumber: "",
          phoneAreaCode: "",
          phoneCountryCode: "",
        },
      ],
      isSupplier: false,
      isCustomer: false,
      salesDefaultLineAmountType: undefined,
      purchasesDefaultLineAmountType: undefined,
      defaultCurrency: undefined,
      xeroNetworkKey: undefined,
      salesDefaultAccountCode: undefined,
      purchasesDefaultAccountCode: undefined,
      salesTrackingCategories: undefined,
      purchasesTrackingCategories: undefined,
      trackingCategoryName: undefined,
      trackingCategoryOption: undefined,
      paymentTerms: undefined,
      updatedDateUTC: {
      },
      contactGroups: [
      ],
      website: undefined,
      brandingTheme: undefined,
      batchPayments: undefined,
      discount: undefined,
      balances: undefined,
      attachments: undefined,
      hasAttachments: false,
      validationErrors: undefined,
      hasValidationErrors: false,
      statusAttributeString: undefined,
    },
    {
      contactID: "6b1dc34f-d7ba-4672-be44-aa58a8d6d9ca",
      mergedToContactID: undefined,
      contactNumber: undefined,
      accountNumber: undefined,
      contactStatus: "ACTIVE",
      name: "Square",
      firstName: undefined,
      lastName: undefined,
      companyNumber: undefined,
      emailAddress: "",
      skypeUserName: undefined,
      contactPersons: [
      ],
      bankAccountDetails: "",
      taxNumber: undefined,
      accountsReceivableTaxType: undefined,
      accountsPayableTaxType: undefined,
      addresses: [
        {
          addressType: "STREET",
          addressLine1: undefined,
          addressLine2: undefined,
          addressLine3: undefined,
          addressLine4: undefined,
          city: "",
          region: "",
          postalCode: "",
          country: "",
          attentionTo: undefined,
        },
        {
          addressType: "POBOX",
          addressLine1: undefined,
          addressLine2: undefined,
          addressLine3: undefined,
          addressLine4: undefined,
          city: "",
          region: "",
          postalCode: "",
          country: "",
          attentionTo: undefined,
        },
      ],
      phones: [
        {
          phoneType: "DDI",
          phoneNumber: "",
          phoneAreaCode: "",
          phoneCountryCode: "",
        },
        {
          phoneType: "DEFAULT",
          phoneNumber: "",
          phoneAreaCode: "",
          phoneCountryCode: "",
        },
        {
          phoneType: "FAX",
          phoneNumber: "",
          phoneAreaCode: "",
          phoneCountryCode: "",
        },
        {
          phoneType: "MOBILE",
          phoneNumber: "",
          phoneAreaCode: "",
          phoneCountryCode: "",
        },
      ],
      isSupplier: true,
      isCustomer: false,
      salesDefaultLineAmountType: undefined,
      purchasesDefaultLineAmountType: undefined,
      defaultCurrency: undefined,
      xeroNetworkKey: undefined,
      salesDefaultAccountCode: undefined,
      purchasesDefaultAccountCode: undefined,
      salesTrackingCategories: undefined,
      purchasesTrackingCategories: undefined,
      trackingCategoryName: undefined,
      trackingCategoryOption: undefined,
      paymentTerms: undefined,
      updatedDateUTC: {
      },
      contactGroups: [
      ],
      website: undefined,
      brandingTheme: undefined,
      batchPayments: undefined,
      discount: undefined,
      balances: undefined,
      attachments: undefined,
      hasAttachments: false,
      validationErrors: undefined,
      hasValidationErrors: false,
      statusAttributeString: undefined,
    },
    {
      contactID: "98e8d2d2-a956-4146-8d8a-c56ad111c960",
      mergedToContactID: undefined,
      contactNumber: undefined,
      accountNumber: undefined,
      contactStatus: "ACTIVE",
      name: "Google",
      firstName: undefined,
      lastName: undefined,
      companyNumber: undefined,
      emailAddress: undefined,
      skypeUserName: undefined,
      contactPersons: [
      ],
      bankAccountDetails: undefined,
      taxNumber: "77-0493581",
      accountsReceivableTaxType: undefined,
      accountsPayableTaxType: undefined,
      addresses: [
        {
          addressType: "POBOX",
          addressLine1: "1600 Amphitheatre Pkwy",
          addressLine2: undefined,
          addressLine3: undefined,
          addressLine4: undefined,
          city: "Mountain View",
          region: "CA",
          postalCode: "94043",
          country: "USA",
          attentionTo: undefined,
        },
        {
          addressType: "STREET",
          addressLine1: "1600 Amphitheatre Pkwy",
          addressLine2: undefined,
          addressLine3: undefined,
          addressLine4: undefined,
          city: "Mountain View",
          region: "CA",
          postalCode: "94043",
          country: "USA",
          attentionTo: undefined,
        },
      ],
      phones: [
        {
          phoneType: "DDI",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
        {
          phoneType: "DEFAULT",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
        {
          phoneType: "FAX",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
        {
          phoneType: "MOBILE",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
      ],
      isSupplier: true,
      isCustomer: false,
      salesDefaultLineAmountType: undefined,
      purchasesDefaultLineAmountType: undefined,
      defaultCurrency: "USD",
      xeroNetworkKey: undefined,
      salesDefaultAccountCode: undefined,
      purchasesDefaultAccountCode: undefined,
      salesTrackingCategories: undefined,
      purchasesTrackingCategories: undefined,
      trackingCategoryName: undefined,
      trackingCategoryOption: undefined,
      paymentTerms: {
        bills: {
          day: 0,
          type: "DAYSAFTERBILLDATE",
        },
        sales: undefined,
      },
      updatedDateUTC: {
      },
      contactGroups: [
      ],
      website: undefined,
      brandingTheme: undefined,
      batchPayments: undefined,
      discount: undefined,
      balances: undefined,
      attachments: undefined,
      hasAttachments: false,
      validationErrors: undefined,
      hasValidationErrors: false,
      statusAttributeString: undefined,
    },
    {
      contactID: "9862f91a-2715-4185-a913-fc6c61584dff",
      mergedToContactID: undefined,
      contactNumber: undefined,
      accountNumber: "1258168350",
      contactStatus: "ACTIVE",
      name: "Adobe Creative Cloud",
      firstName: undefined,
      lastName: undefined,
      companyNumber: undefined,
      emailAddress: undefined,
      skypeUserName: undefined,
      contactPersons: [
      ],
      bankAccountDetails: undefined,
      taxNumber: undefined,
      accountsReceivableTaxType: undefined,
      accountsPayableTaxType: undefined,
      addresses: [
        {
          addressType: "POBOX",
          addressLine1: "345 Park Ave",
          addressLine2: undefined,
          addressLine3: undefined,
          addressLine4: undefined,
          city: "San Jose",
          region: "CA",
          postalCode: "95110",
          country: "USA",
          attentionTo: undefined,
        },
        {
          addressType: "STREET",
          addressLine1: "345 Park Ave",
          addressLine2: undefined,
          addressLine3: undefined,
          addressLine4: undefined,
          city: "San Jose",
          region: "CA",
          postalCode: "95110",
          country: "USA",
          attentionTo: undefined,
        },
      ],
      phones: [
        {
          phoneType: "DDI",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
        {
          phoneType: "DEFAULT",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
        {
          phoneType: "FAX",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
        {
          phoneType: "MOBILE",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
      ],
      isSupplier: true,
      isCustomer: false,
      salesDefaultLineAmountType: undefined,
      purchasesDefaultLineAmountType: undefined,
      defaultCurrency: "USD",
      xeroNetworkKey: undefined,
      salesDefaultAccountCode: undefined,
      purchasesDefaultAccountCode: undefined,
      salesTrackingCategories: undefined,
      purchasesTrackingCategories: undefined,
      trackingCategoryName: undefined,
      trackingCategoryOption: undefined,
      paymentTerms: undefined,
      updatedDateUTC: {
      },
      contactGroups: [
      ],
      website: undefined,
      brandingTheme: undefined,
      batchPayments: undefined,
      discount: undefined,
      balances: undefined,
      attachments: undefined,
      hasAttachments: false,
      validationErrors: undefined,
      hasValidationErrors: false,
      statusAttributeString: undefined,
    },
    {
      contactID: "c30206e2-c34c-4dc4-966b-5ef978d17372",
      mergedToContactID: undefined,
      contactNumber: undefined,
      accountNumber: undefined,
      contactStatus: "ACTIVE",
      name: "Envato Elements",
      firstName: undefined,
      lastName: undefined,
      companyNumber: undefined,
      emailAddress: undefined,
      skypeUserName: undefined,
      contactPersons: [
      ],
      bankAccountDetails: undefined,
      taxNumber: "EU372010001",
      accountsReceivableTaxType: undefined,
      accountsPayableTaxType: undefined,
      addresses: [
        {
          addressType: "POBOX",
          addressLine1: "PO Box 16122",
          addressLine2: "Collins Street West",
          addressLine3: undefined,
          addressLine4: undefined,
          city: "Melbourne",
          region: "Victoria",
          postalCode: "8007",
          country: "Australia",
          attentionTo: undefined,
        },
        {
          addressType: "STREET",
          addressLine1: "PO Box 16122",
          addressLine2: "Collins Street West",
          addressLine3: undefined,
          addressLine4: undefined,
          city: "Melbourne",
          region: "Victoria",
          postalCode: "8007",
          country: "Australia",
          attentionTo: undefined,
        },
      ],
      phones: [
        {
          phoneType: "DDI",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
        {
          phoneType: "DEFAULT",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
        {
          phoneType: "FAX",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
        {
          phoneType: "MOBILE",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
      ],
      isSupplier: true,
      isCustomer: false,
      salesDefaultLineAmountType: undefined,
      purchasesDefaultLineAmountType: undefined,
      defaultCurrency: "USD",
      xeroNetworkKey: undefined,
      salesDefaultAccountCode: undefined,
      purchasesDefaultAccountCode: undefined,
      salesTrackingCategories: undefined,
      purchasesTrackingCategories: undefined,
      trackingCategoryName: undefined,
      trackingCategoryOption: undefined,
      paymentTerms: undefined,
      updatedDateUTC: {
      },
      contactGroups: [
      ],
      website: undefined,
      brandingTheme: undefined,
      batchPayments: undefined,
      discount: undefined,
      balances: undefined,
      attachments: undefined,
      hasAttachments: false,
      validationErrors: undefined,
      hasValidationErrors: false,
      statusAttributeString: undefined,
    },
    {
      contactID: "6d8dfa30-e5b2-4d9f-b547-4fb9afbc06aa",
      mergedToContactID: undefined,
      contactNumber: undefined,
      accountNumber: undefined,
      contactStatus: "ACTIVE",
      name: "Vulcan Materials Company - Conroe Plant",
      firstName: "Karl",
      lastName: "Wighaman",
      companyNumber: undefined,
      emailAddress: "wighamank@vmcmail.com",
      skypeUserName: undefined,
      contactPersons: [
      ],
      bankAccountDetails: undefined,
      taxNumber: undefined,
      accountsReceivableTaxType: undefined,
      accountsPayableTaxType: undefined,
      addresses: [
        {
          addressType: "POBOX",
          addressLine1: "1200 Urban Center Dr",
          addressLine2: undefined,
          addressLine3: undefined,
          addressLine4: undefined,
          city: "Birmingham",
          region: "AL",
          postalCode: "35242",
          country: "USA",
          attentionTo: "Accounts Payable",
        },
        {
          addressType: "STREET",
          addressLine1: "9490 FM 1485 Rd",
          addressLine2: undefined,
          addressLine3: undefined,
          addressLine4: undefined,
          city: "Conroe",
          region: "TX",
          postalCode: "77306",
          country: "USA",
          attentionTo: "Vulcan - Conroe Plant",
        },
      ],
      phones: [
        {
          phoneType: "DDI",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
        {
          phoneType: "DEFAULT",
          phoneNumber: "4445920",
          phoneAreaCode: "713",
          phoneCountryCode: "1",
        },
        {
          phoneType: "FAX",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
        {
          phoneType: "MOBILE",
          phoneNumber: undefined,
          phoneAreaCode: undefined,
          phoneCountryCode: undefined,
        },
      ],
      isSupplier: false,
      isCustomer: false,
      salesDefaultLineAmountType: undefined,
      purchasesDefaultLineAmountType: undefined,
      defaultCurrency: undefined,
      xeroNetworkKey: undefined,
      salesDefaultAccountCode: undefined,
      purchasesDefaultAccountCode: undefined,
      salesTrackingCategories: undefined,
      purchasesTrackingCategories: undefined,
      trackingCategoryName: undefined,
      trackingCategoryOption: undefined,
      paymentTerms: {
        bills: undefined,
        sales: {
          day: 0,
          type: "DAYSAFTERBILLDATE",
        },
      },
      updatedDateUTC: {
      },
      contactGroups: [
      ],
      website: "https://www.vulcanmaterials.com/",
      brandingTheme: undefined,
      batchPayments: undefined,
      discount: undefined,
      balances: undefined,
      attachments: undefined,
      hasAttachments: false,
      validationErrors: undefined,
      hasValidationErrors: false,
      statusAttributeString: undefined,
    },
  ]